### ISSUE TITLE
DataView Hostdependency does not exist

### ISSUE THREAD

**Issue by edwardofclt** [invliD/icingaweb2-module-statusmap#11]
This error is produced on first click of the status map link in the toolbar.

```
DataView Hostdependency does not exist

#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(254): Icinga\Module\Monitoring\Backend\MonitoringBackend->buildViewClassName(String)
#1 /usr/share/icingaweb2/modules/statusmap/application/controllers/IndexController.php(36): Icinga\Module\Monitoring\Backend\MonitoringBackend->from(String, Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): StatusMap_IndexController->indexAction()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(303): Zend_Controller_Action->dispatch(String)
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(56): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(409): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}
```

**Comment by invliD** [comment]
Please read the readme.
