### ISSUE TITLE
doesn't work with icingaweb 2.2.0

### ISSUE THREAD

**Issue by ghost** [invliD/icingaweb2-module-statusmap#4]
Hi,

thank you for this wonderful module. However, it doesn't work for me with icingaweb2 2.2.0 anymore. I get this error message on the /icingaweb2/statusmap page:

```
#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(259): Icinga\Module\Monitoring\Backend\MonitoringBackend->buildViewClassName('hostdependency')
#1 /usr/share/icingaweb2/modules/statusmap/application/controllers/IndexController.php(36): Icinga\Module\Monitoring\Backend\MonitoringBackend->from('hostdependency', Array)
#2 /usr/share/php/Zend/Controller/Action.php(516): StatusMap_IndexController->indexAction()
#3 /usr/share/php/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(56): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(383): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}
```

I already tried by adding the second symlink in the open pull-request from ClemensBW, but this didn't help either.

Do you have any ideas on how to proceed? Would love to get it working again.

Regards,
Daniel

**Comment by invliD** [comment]
I can't confirm the issue even though I'm running on Icingaweb2 2.2.0, too. Please try the instructions from README again, the symlink in #2 was incorrect.

**Comment by faust64** [comment]
I confirm having upgraded to icingaweb2.4.0: links broke, restoring them fixed, statusmap still perfectly works.
Are your *really* sure your links are right? That error message looks a lot like mine.
